package complaint;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

@WebServlet("/submitComplaint")
public class complaintController extends HttpServlet {

    private static final long serialVersionUID = 1L;
    private ComplaintDAO complaintDAO;

    @Override
    public void init() {
        complaintDAO = new ComplaintDAO();
    }

    // Handle the GET request to show the complaint form and fetch all complaints
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // Fetch all complaints (no filtering by email)
        List<complaint> complaints = complaintDAO.listAllComplaints();

        // Set the complaints list as an attribute to display in JSP
        request.setAttribute("complaints", complaints);
        request.getRequestDispatcher("/custComplaint.jsp").forward(request, response);
    }

    // Handle the POST request to save the complaint
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String complaintDescription = request.getParameter("complaintDescription");
        String cmpPriority = request.getParameter("cmp_priority");

        // Create a new complaint object (no email needed)
        complaint newComplaint = new complaint(
                0,  // complaintID will be auto-generated by DB
                complaintDescription,
                cmpPriority,
                "Open",  // Default status for new complaints
                new java.util.Date() // Set the current date
        );

        // Save the complaint to the database
        boolean isSaved = complaintDAO.saveComplaint(newComplaint);

        // Set an attribute to indicate success or failure
        if (isSaved) {
            request.setAttribute("successMessage", "Complaint submitted successfully!");
        } else {
            request.setAttribute("errorMessage", "Failed to submit the complaint. Please try again.");
        }

        // Fetch the updated list of complaints (after submission)
        List<complaint> complaints = complaintDAO.listAllComplaints();
        request.setAttribute("complaints", complaints);

        // Forward back to the same page (custComplaint.jsp)
        request.getRequestDispatcher("/custComplaint.jsp").forward(request, response);
    }
}

